import requests

token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjQxMTYsInJvbGUiOm51bGwsImRhdGEiOnsiaWQiOjQxMTYsIm5hbWUiOiJBdGFtdXJhdG92IEJla3phZCBLdWRyYXQgdWxpIiwiZW1haWwiOiJhdGFtdXJhdG92YmVnem9kQGdtYWlsLmNvbSIsInJvbGUiOm51bGwsImFwaV90b2tlbiI6bnVsbCwic3RhdHVzIjoiYWN0aXZlIiwic21zX2FwaV9sb2dpbiI6ImVza2l6MiIsInNtc19hcGlfcGFzc3dvcmQiOiJlJCRrIXoiLCJ1el9wcmljZSI6NTAsInVjZWxsX3ByaWNlIjoxMTUsInRlc3RfdWNlbGxfcHJpY2UiOm51bGwsImJhbGFuY2UiOjUwMDAsImlzX3ZpcCI6MCwiaG9zdCI6InNlcnZlcjEiLCJjcmVhdGVkX2F0IjoiMjAyMy0wNS0zMVQxMzowNDoxNS4wMDAwMDBaIiwidXBkYXRlZF9hdCI6IjIwMjMtMDUtMzFUMTM6MDU6MzAuMDAwMDAwWiIsIndoaXRlbGlzdCI6bnVsbCwiaGFzX3BlcmZlY3R1bSI6MH0sImlhdCI6MTY4NTUzOTQwNCwiZXhwIjoxNjg4MTMxNDA0fQ.YUPk0JZBJIaIn9B2tgPq1xzqQqrerOBYARX1xuWw86Y"

def send_sms(phone, otp):
    msg = f"Шестизначный код {otp}"



